language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 6.9
dist: trusty
sudo: required
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
before_script:
  - npm prune
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
script:
  - ng lint
  - ng test --single-run --code-coverage
  - ng e2e
after_success:
  - npm run report-coverage
branches:
  only:
    - master
