codecov:
  token: 6965d658-511b-4e22-9cea-8e17201dc071
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "src/models"
  - "src/mocks"
  - "src/config"
  - "src/data"
  - "src/assets"
  - "src/polyfills.*"
